# XXX(stephentu): this is the only way I know how to tell travis ci we want an
# OS X virtual machine
language: objective-c
notifications:
  email: false
  slack:
    secure: "UvaKdilhLmefDk+cvmGWJI8y78Qhd4t1g/nhvENGtwcVstcnR/opnJajowVjMHlphNGaCON+6wdqeVTezMAjRNCTdMGK0nCthv0DdqcyCYFsl/1ddJJ0G6KYhBIPK5GxaYVTuvquipoUrelMfo8snevU44QdYB836JFZfHPAHf0="
before_install:
  - gcc -v
  - c++ -v
  # XXX(stephentu): HACK
  # see https://github.com/datamicroscopes/common/issues/1
  - sudo mv `which gcc-4.2` `which gcc-4.2`-old
  - wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-MacOSX-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes binstar conda-build jinja2
  - conda config --add channels distributions
  - conda config --add channels datamicroscopes
env:
  - secure: "k1lj4j8iPn+bZXsbOolWZjUPkeUkFLOOA/L/Amjf8BH1+IxHlqNq8IwnynSKrPVRkDVMHpUY4WoK2+4/M1mFPyT7VMU7sL45oJy9wtZ9dz4FrTIRZny98lbWHOuRpf69v36/IpBeyX+krcJI4SLjuRpOsEoSJA+VA4hj7k25cX4="
install:
  - echo "nothing to do"
script:
  # this order matters!
  - python build.py --username datamicroscopes --password "$BINSTAR_PASSWORD" --project common --remove-before-build
  - python build.py --username datamicroscopes --password "$BINSTAR_PASSWORD" --project mixturemodel --remove-before-build
  - python build.py --username datamicroscopes --password "$BINSTAR_PASSWORD" --project irm --remove-before-build
  - python build.py --username datamicroscopes --password "$BINSTAR_PASSWORD" --project kernels --remove-before-build
